# Python for deep learning

In [16]:
import os
if  not os.path.isdir('./training'):
  !cd /content/ && git clone https://github.com/MontpellierRessourcesImagerie/DL_EXP_PC.git && cp -r DL_EXP_PC/data . && cp -r DL_EXP_PC/training .
  %cd DL_EXP_PC

## Cell 11

```python
prediction = model.predict(np.array([[128/255]*N*N]))
classPrediction = model.predict_classes(np.array([[128/255]*N*N]))
print("p:", prediction.flatten(), "c:", classPrediction.flatten())
```

In cell 10 we use the trained model to make a prediction on a single input vector.

We build and train the simple model we used before again.

In [1]:
import numpy as np
X = np.random.rand(1000, 9)
y = np.array([int(round(sum(xv)/len(xv))) for xv in X])
print(X[0:9])
print(y[0:9])

[[0.78449293 0.4450239  0.24956978 0.29892577 0.89719575 0.67521629
  0.87022643 0.51161524 0.7404586 ]
 [0.50048544 0.59244918 0.56587965 0.81743002 0.86286374 0.86492517
  0.83557717 0.01080788 0.9107864 ]
 [0.63063699 0.82823561 0.15778714 0.85168385 0.40060874 0.15861522
  0.3530732  0.28126329 0.31443729]
 [0.30388407 0.44542491 0.60852142 0.89408443 0.35758309 0.16512139
  0.53849303 0.22197047 0.1766673 ]
 [0.81720365 0.14347139 0.69588539 0.23112109 0.54112079 0.34649474
  0.02841207 0.52050043 0.13214563]
 [0.10991633 0.18980094 0.74931736 0.73054308 0.33648484 0.63124249
  0.67058359 0.09945681 0.39901845]
 [0.02801242 0.70559405 0.19742836 0.26132443 0.89666072 0.75645048
  0.33973158 0.79119051 0.60225982]
 [0.06463632 0.83245597 0.35066521 0.55156138 0.25679072 0.43986709
  0.81733135 0.49912386 0.78190666]
 [0.18606974 0.56205549 0.00935219 0.69496586 0.50185723 0.84456457
  0.90006546 0.40022903 0.90075564]]
[1 1 0 0 0 0 1 1 1]


In [2]:
%%time
from keras.models import Sequential
from keras.layers import Dense
from IPython.display import SVG
N=3
model = Sequential()
model.add(Dense(N*N-1, input_dim=(N*N), activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='rmsprop', metrics=['accuracy'])
history = model.fit(X, y, validation_split=0.25, epochs=1000, batch_size=256, verbose=0)
print("Loss: ", history.history['val_loss'][-1], "Accuracy: ", history.history['val_accuracy'][-1])

Using TensorFlow backend.


Loss:  0.10502414405345917 Accuracy:  0.9800000190734863
CPU times: user 6.26 s, sys: 786 ms, total: 7.05 s
Wall time: 4.33 s


In [4]:
prediction = model.predict(np.array([[128/255]*N*N]))
print(prediction)

[[0.5102043]]


The prediction method of the model returns a list of predictions, one for each input vector in the input array. However a model can also have a vector instead of a scalar as a prediction result. Therefore result is a list of lists.

Here a result for two input vectors:

In [7]:
inputVectors = np.array([[128/255]*N*N, [64/255]*N*N])
print(inputVectors)

[[0.50196078 0.50196078 0.50196078 0.50196078 0.50196078 0.50196078
  0.50196078 0.50196078 0.50196078]
 [0.25098039 0.25098039 0.25098039 0.25098039 0.25098039 0.25098039
  0.25098039 0.25098039 0.25098039]]


In [8]:
prediction = model.predict(inputVectors)
print(prediction)
classPrediction = model.predict_classes(inputVectors)
print(classPrediction)

[[5.1020473e-01]
 [8.1294303e-07]]
[[1]
 [0]]


To get rid of the inner arrays, we use the method ``flatten()`` of the numpy array.

In [10]:
print(prediction.flatten())
print(classPrediction.flatten())

[5.1020473e-01 8.1294303e-07]
[1 0]
